version: '3'

services:
  web:
    build: web
    ports:
      - 5000:5000
    networks:
      - backend
    depends_on:
      - mongo #Web is dependent on database
  mongo:
    image: mongo:latest
    restart: unless-stopped
    networks:
      - backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    #- ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - 27017:27017
      
networks:
  backend:
    driver: bridge
